#!/bin/bash

#Napisz skrypt który zbiera o użytkowniku dane takie jak: imię, nazwisko, wiek, położenie katalogu domowego, typ systemu operacyjnego oraz login. Do zbierania trzech ostatnich wykorzystaj zmienne specjalne. Na końcu wyświetl te dane.

read -p "Podaj swoje imie: " imie
read -p "Podaj swoje nazwisko: " nazwisko
read -p "Podaj swoj wiek: " wiek

echo -e "\nImię: $imie"
echo Nazwisko: $nazwisko
echo Wiek: $wiek
echo Katalog domowy: $HOME
echo System: $OSTYPE
echo Login: $USER
