#!/bin/bash

#Stworzyć dwie tablice 4-elementowe, dodać do siebie odpowiadające wartości po indeksach i wyświetlić wynik.

tablica1=(5 10 15 20)
tablica2=(60 10 30 50)

echo Tablica1 ${tablica1[*]}
echo Tablica2 ${tablica2[*]}

tablica3=($[${tablica1[0]}+${tablica2[0]}] $[${tablica1[1]}+${tablica2[1]}] $[${tablica1[2]}+${tablica2[2]}] $[${tablica1[3]}+${tablica2[3]}])
echo Wynik dodawania ${tablica3[*]}
