#!/bin/bash

#Napisać taki skrypt, zdefiniowana jest tablica 5-elementowa z następującymi wartościami: 2 4 -3 8 7. 
#Następnie dodać 2 do ostatniego elementu tablicy oraz odjąć 1 od elementu o indeksie trzy. 
#Usunąć element zerowy i dodać nowy jako ostatni element tej tablicy, który jest równy liczbie wszystkich elementów tej tablicy. 
#W wyniku wykonania skryptu ma się pojawić komunikat:
#START array=(2 4 -3 8 7)
#END array=(4 -3 7 9 4)

tablica=(2 4 -3 8 7)
echo "Początkowa tablica: ${tablica[*]}"

tablica[4]=$[${tablica[4]}+2]
tablica[3]=$[${tablica[3]}-1]
unset tablica[0]
tablica[5]=4

echo "Tablica po zmianach: ${tablica[*]}"
