#!/bin/bash

#Napisz skrypt który zbiera o użytkowniku dane takie jak: imię, nazwisko, wiek, położenie katalogu domowego, typ systemu operacyjnego oraz login.
#Do zbierania trzech ostatnich wykorzystaj zmienne specjalne. Dane zostaną zapisane w pliku nazywającym się tak samo jak nazwisko wpisane przez użytkownika.

read -p "Podaj swoje imie: " imie
read -p "Podaj swoje nazwisko: " nazwisko
read -p "Podaj swoj wiek: " wiek
echo Imię: $imie >>$nazwisko
echo Nazwisko: $nazwisko  >>$nazwisko
echo Wiek: $wiek >>$nazwisko
echo Katalog domowy: $HOME >>$nazwisko
echo System: $OSTYPE >>$nazwisko
echo Login: $USER >>$nazwisko
